robotology/whole-body-estimators

devices/baseEstimatorV1/app/robots/iCubGazeboV2_5/estimators/fbe-analogsens.xml, devices/baseEstimatorV1/include/baseEstimatorV1.h, devices/baseEstimatorV1/scope/base_scope.xml, devices/baseEstimatorV1/src/baseEstimatorV1.cpp, devices/baseEstimatorV1/thrifts/floatingBaseEstimationRPC.thrift
This PR adds resetIMU methods to the estimator.
The proper functioning of fusion between legged odometry and head/root link IMU was also tested.
=> [fbeV1] add resetIMU methods and test estimation with root/head imu

devices/baseEstimatorV1/include/baseEstimatorV1.h, devices/baseEstimatorV1/src/baseEstimatorV1.cpp, devices/baseEstimatorV1/src/configureEstimator.cpp, devices/baseEstimatorV1/src/fbeRobotInterface.cpp
This PR does the following,
- computes COM state from estimated base pose, base velocity and kinematic measurements
The COM state is available on the port
`/` estimator-prefix `/center_of_mass/state:o` in serialziation `x  y z vx vy vz` 
- fixes deprecation of yarp::os::Mutex and yarp::os::LockGuard by using std::mutex and std::lock_guard
cc @S-Dafarra
=> [fbeV1] Publishing COM computed from estimated base state

devices/baseEstimatorV1/src/baseEstimatorV1.cpp
Publishing during the initialization step was streaming zero values for the published quantities which might undesirable when compared to not having data.
cc @S-Dafarra
=> Avoid publishing during initialization

.github/workflows/ci.yml, CMakeLists.txt, README.md
As a consequence of adding workflows,
- Updated dependencies
-  Windows compilation was fixed by minor modifications to CMakeLists.txt
Additionally,
- Updated Authors
=> Add Github Workflow to check compilation in Windows, Ubuntu and MacOS (latest)

.github/workflows/ci.yml
- Achieve faster workflow CI builds through,
- pre-compiled vcpkg archives
- caching source-based dependency builds
- Add release based versioning for source-based dependencies
Inspired and duplicated from
- https://github.com/robotology/idyntree/pull/655
- https://github.com/dic-iit/bipedal-locomotion-controllers/pull/32
- https://github.com/dic-iit/element_jet-cat-turbines/pull/223
=> [Actions] Add cache action to cache source-based dependency builds and add release versioning to source-based dependencies 

devices/wholeBodyDynamics/app/launch-wholebodydynamics-icub-four-fts.xml, devices/wholeBodyDynamics/app/launch-wholebodydynamics-icub-six-fts-sim.xml, devices/wholeBodyDynamics/app/launch-wholebodydynamics-icub-six-fts.xml, devices/wholeBodyDynamics/app/launch-wholebodydynamics-icubheidelberg01.xml
Please see https://github.com/robotology/codyco-modules/pull/280 __Restore compatibility with YARP 3.2.0__ for the original PR and related issue.
This PR adds changes to launch-wholebodydynamics-*.xml configuration files.
=> [devices][wholeBodyDynamics] replicate codyco-modules PR #280 Restore compatibility with YARP 3.2.0

CHANGELOG.md, devices/baseEstimatorV1/include/baseEstimatorV1.h, devices/genericSensorClient/GenericSensorClient.cpp, devices/genericSensorClient/GenericSensorClient.h, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.h
This PR addresses the following changes in wholebodydynamics device,
- Handles yarp::os::Mutex deprecation with std::mutex and std::lock_guard
- Handles yarp::dev::IControlMode2 deprecation with yarp::dev::IControlMode
- Handles iDynTree/iCub/skinDynLibConversions deprecation with iDynTree/skinDynLibConversions
- Additional changes related to deprecations in LockGuard and ConstString specifications in `wholebodydynamics`, `genericSensorClient` and `baseEstimatorV1`.
Fixes #57
=> [wholebodyDynamics] Fix YARP and iDynTree related deprecations

README.md
* YARP_DATA_DIRS only need to contain `share/yarp` 
* Clarify how to use whole-body-estimators with robotology-superbuild
=> Some fixes in README

CMakeLists.txt, devices/baseEstimatorV1/CMakeLists.txt
See https://github.com/robotology/osqp-eigen/issues/61 for details. In brief, when using ``OsqpEigen`` in ``devel``, by a chain reaction,  this repo fails to compile.
=> Finding Eigen3 and properly link it when using EigenHelpers.

.github/workflows/ci.yml
iDynTree compilation was failing in Windows Visual Studio due to a missing `<string>` header in Triplets.h (Original issue https://github.com/robotology/idyntree/issues/671). This was reflected in our CI workflow as well, See [here](https://github.com/robotology/whole-body-estimators/runs/740774705?check_suite_focus=true). 
This was fixed in https://github.com/robotology/idyntree/pull/672.
Related issue: https://github.com/dic-iit/bipedal-locomotion-framework/pull/49
=> Require iDynTree v1.1.0 in ci.yml

devices/baseEstimatorV1/app/robots/iCubGazeboV2_5/launch-fbe-analogsens.xml, devices/baseEstimatorV1/app/robots/iCubGenova04/launch-fbe-analogsens.xml, devices/baseEstimatorV1/include/baseEstimatorV1.h, devices/baseEstimatorV1/src/baseEstimatorV1.cpp
- Removed a method updateBaseVelocityWithIMU() which was unused and the internal computations seemed to be wrong. (missing an adjoint velocity transform from IMU frame to base frame)
- Removed redundant opening of `controlboard` devices, which is unused by the estimator device, since we open a remotecontrolboardremapper and the estimator device attaches to this remapper. Thanks to @diegoferigo for spotting this.
- Update documentation. Fixes #81.
=> Remove unused code, fix configuration and update documentation 

CHANGELOG.md, devices/wholeBodyDynamics/SixAxisForceTorqueMeasureHelpers.cpp, devices/wholeBodyDynamics/SixAxisForceTorqueMeasureHelpers.h, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.h, idl/wholeBodyDynamics_IDLServer/autogenerated/include/wholeBodyDynamics_IDLServer.h, idl/wholeBodyDynamics_IDLServer/autogenerated/src/wholeBodyDynamics_IDLServer.cpp, idl/wholeBodyDynamics_IDLServer/wholeBodyDynamics_IDLServer.thrift
This PR ports the functionality of considering temperature coefficients in the FT sensors and allows the user to enable if he wants to use an FT offset estimated offline.
It was orignally in [codyco-modules](https://github.com/robotology/codyco-modules/pull/281) and now ported to this repo.
=> Add support for compensating temperature in Force/Torque sensors readings and for specify user offline offset 

.github/workflows/ci.yml
See,
- https://github.com/robotology/idyntree/pull/748
- https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> [workflows] remove use of deprecated set-env in Github Action

CHANGELOG.md, devices/wholeBodyDynamics/app/CMakeLists.txt, devices/wholeBodyDynamics/app/launch-wholebodydynamics-icub-eight-fts-sim.xml, devices/wholeBodyDynamics/app/wholebodydynamics-icub-external-eight-fts-sim.xml
Requires the iCubGazeboV3 URDF model to contain the IMU sensor added in its `head` link.
This is a pending issue in https://github.com/robotology/icub-models/issues/62.
Temporarily, this can be fixed by adding to the URDF, 
``` xml
<gazebo reference="head">
<sensor name="head_imu_acc_1x1" type="imu">
<always_on>1</always_on>
<update_rate>100</update_rate>
<pose>0.0 0.0 0.0 0.0 0.0 0.0</pose>
<plugin name="iCub_yarp_gazebo_plugin_IMU" filename="libgazebo_yarp_imu.so">
<yarpConfigurationFile>model://iCub/conf_icub3/gazebo_icub_inertial.ini</yarpConfigurationFile>
</plugin>
</sensor>
</gazebo>
<sensor name="head_imu_acc_1x1" type="accelerometer">
<parent link="head"/>
<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
</sensor>
```
This is done in …
=> Add wholeBodyDynamics configuration files for iCubGazeboV3

CHANGELOG.md, devices/virtualAnalogClient/VirtualAnalogClient.cpp, devices/virtualAnalogClient/VirtualAnalogClient.h, devices/virtualAnalogRemapper/VirtualAnalogRemapper.cpp, devices/virtualAnalogRemapper/VirtualAnalogRemapper.h
There were a few unaddressed const string deprecations in virtual analog remapper and clients.
=> Fix unaddressed yarp::os::ConstString deprecation

CHANGELOG.md, devices/wholeBodyDynamics/README.md, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.h
Only if the specific group is present in configuration file, the relevant feature is enabled.
Otherwise, fully compatible with default behavior.
=> wholeBodyDynamics: add feature to use MAS interface based  RFE IMU 

devices/baseEstimatorV1/CMakeLists.txt
Fix https://github.com/robotology/whole-body-estimators/issues/100 .
=> Link libraries used by baseEstimatorV1 device

CHANGELOG.md, devices/wholeBodyDynamics/README.md, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp
Reference issue in `iDynTree` https://github.com/robotology/idyntree/issues/829
The PR appends fixed joints `l_foot_ft_sensor`, `r_foot_ft_sensor` in case they are omitted because the corresponding F/T sensors are not included in the model.
This will enable adding the link frames `l_foot` and `r_foot` in the config group `WBD_OUTPUT_EXTERNAL_WRENCH_PORTS` even when the fee F/T sensors are removed from the URDF model.
=> [WBD] Add fixed joints l_foot_ft_sensor and r_foot_ft_sensor explicitly

CHANGELOG.md, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.h, idl/wholeBodyDynamics_IDLServer/autogenerated/include/wholeBodyDynamics_IDLServer.h, idl/wholeBodyDynamics_IDLServer/autogenerated/src/wholeBodyDynamics_IDLServer.cpp, idl/wholeBodyDynamics_IDLServer/wholeBodyDynamics_IDLServer.thrift
Reference issue https://github.com/dic-iit/element_ironcub-estimation/issues/93
This PR adds another `yarp rpc` fucntion `calibStandingWithJetsiRonCubMk1`, to be used only with `iRonCub-Mk1` model/robot.
- The function is intended to be used when the jets in `iRonCub-Mk1` are ON with idle thrust value.
- The function is similar to `calibStanding` with an addition of other 4 known-wrench contacts.
=> [WBD] Add `calibStandingWithJetsiRonCubMk1` rpc command

CHANGELOG.md, devices/baseEstimatorV1/CMakeLists.txt, devices/genericSensorClient/CMakeLists.txt, devices/virtualAnalogClient/CMakeLists.txt, devices/virtualAnalogRemapper/CMakeLists.txt, devices/wholeBodyDynamics/CMakeLists.txt
See https://github.com/robotology/yarp/issues/2606
=> Add INTERNAL flag to devices cmake to support proper compilation when some cmake flags are unspecified

.github/workflows/ci.yml, CHANGELOG.md, CMakeLists.txt, devices/baseEstimatorV1/include/baseEstimatorV1.h
In https://github.com/robotology/idyntree/pull/770 the `getSensorIndex` variant that takes `std::ptrdiff_t` was deprecated, and it has been removed in the upcoming iDynTree 4 (https://github.com/robotology/idyntree/pull/884). This PR fixes the deprecation warning in iDynTree 3 and the compilation with iDynTree 4.
I also bumped the version of iDynTree used in CI that it was quite old, and prevented the CI to compile correctly this PR.
=> Fix deprecation with iDynTree 3

.github/workflows/conda-ci.yml
While working on https://github.com/robotology/whole-body-estimators/pull/116, I noticed that the current CI is quite slow. In this PR I added a conda-based CI using the template already followed in other repos that should provide feedback on a PR much faster.
=> Add Conda-based Continuous Integration job

devices/wholeBodyDynamics/app/wholebodydynamics-icub3-external-sim.xml
- changes endEffectorWrench into cartesianEndEffectorWrench for the left and right arms
- fix bug for right hand end-effector wrench
=> [WBD-iCubGazeboV3] Make cartesianEndEffectorWrench port similar to iCubGenova09 configuration

CHANGELOG.md, idl/wholeBodyDynamicsSettings/wholeBodyDynamicsSettings.thrift
In YARP 3.6, the Editor internal structure for thrift data structures is now not generated by default. So to fix compilation, we now enable it.
Fix https://github.com/robotology/whole-body-estimators/issues/134 .
=> Fix compilation against YARP 3.6

devices/wholeBodyDynamics/README.md, idl/wholeBodyDynamics_IDLServer/wholeBodyDynamics_IDLServer.thrift
I am adding some lines in the documentation of the RPC commands for `wholeBodyDynamics` as I didn't find them written anywhere except in the code.
For `baseEstimatorV1` I see the documentation is already there. See https://github.com/robotology/whole-body-estimators/tree/ef74e95a4e551604e97a788459997e5aec48415c/devices/baseEstimatorV1
=> [WBD] Add RPC documentation

.github/workflows/conda-ci.yml
`windows-latest` now contains Visual Studio 2022, so to use Visual Studio 2019 let's use `windows-2019`.
=> Fix Windows CI

CHANGELOG.md, devices/genericSensorClient/GenericSensorClient.cpp, devices/genericSensorClient/GenericSensorClient.h
Switch the default carrier for two reasons (both detailed in https://github.com/robotology/yarp/issues/2814#issuecomment-1064943035):
* YARP blocks for 0.25 seconds whenever a UDP receiver is interrupted. The reason of this delay is not clear, but it will not be changed as the effect of such change are unknown due to [Hyrum's Law](https://www.hyrumslaw.com/)
* In general it is not recommended to use a UDP carrier on a stream if there is no other reliable control stream
=> Switch default carrier of `genericSensorClient` device from `udp` to `fast_tcp` to avoid delays up to 0.25 seconds when a receiver is interrupted

CHANGELOG.md, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.h
=> Introduce MAS Read in whole body estimator 

CHANGELOG.md, devices/virtualAnalogClient/VirtualAnalogClient.cpp, devices/virtualAnalogClient/VirtualAnalogClient.h
Fix https://github.com/robotology/whole-body-estimators/issues/158 .
=> Implement VirtualAnalogClient::getAxes to fix compilation against YARP 3.8

CHANGELOG.md, devices/virtualAnalogRemapper/VirtualAnalogRemapper.cpp, devices/virtualAnalogRemapper/VirtualAnalogRemapper.h
Even after https://github.com/robotology/whole-body-estimators/pull/159, the robotology-superbuild Unstable CI was still failing because there was another method to implement, this PR should finally fix compatibility for the future YARP 3.8 .
=> Implement VirtualAnalogRemapper::getAxes to fix compilation with YARP 3.8

.gitignore, CHANGELOG.md, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp
This is a part of the investigation we are doing with @mebbaid using `ergoCubGazeboV1` https://github.com/icub-tech-iit/ergocub-software/issues/35
We couldn't attach both the IMU and the FTs as MAS.
With the previous logic before this PR, the software doesn't distinguish between them. As it seems both devices types implement all the MAS interfaces, including the interfaces `ISixAxisForceTorqueSensors` and `IThreeAxisLinearAccelerometers`.
=> fix attaching both IMU and FTs as MAS network wrappers

CHANGELOG.md, devices/baseEstimatorV1/app/robots/iCubGazeboV2_5/estimators/fbe-analogsens.xml, devices/baseEstimatorV1/app/robots/iCubGazeboV2_5/launch-fbe-analogsens.xml, devices/baseEstimatorV1/app/robots/iCubGenova04/estimators/fbe-analogsens.xml, devices/baseEstimatorV1/app/robots/iCubGenova04/launch-fbe-analogsens.xml, devices/baseEstimatorV1/include/baseEstimatorV1.h, devices/wholeBodyDynamics/README.md, devices/wholeBodyDynamics/app/launch-wholebodydynamics-icub-four-fts.xml, devices/wholeBodyDynamics/app/launch-wholebodydynamics-icub-six-fts-sim.xml, devices/wholeBodyDynamics/app/launch-wholebodydynamics-icub-six-fts.xml, devices/wholeBodyDynamics/app/launch-wholebodydynamics-icub3-sim.xml, devices/wholeBodyDynamics/app/launch-wholebodydynamics-icubheidelberg01.xml, devices/wholeBodyDynamics/app/wholebodydynamics-icub-eth-six-fts.xml, devices/wholeBodyDynamics/app/wholebodydynamics-icub-external-and-can-four-fts.xml, devices/wholeBodyDynamics/app/wholebodydynamics-icub-external-and-can-six-fts.xml, devices/wholeBodyDynamics/app/wholebodydynamics-icub-external-six-fts-sim.xml, devices/wholeBodyDynamics/app/wholebodydynamics-icub3-external-sim.xml, devices/wholeBodyDynamics/app/wholebodydynamics-icubheidelberg01-external.xml, devices/wholeBodyDynamics/app/wholebodydynamics-icubheidelberg01-robot.xml, doc/howto/useTemperatureCoefficientsAndOffsetCompensationInWholeBodyDynamics.md
Revised version of https://github.com/robotology/whole-body-estimators/pull/171 after reviews from @HosameldinMohamed .
Fix https://github.com/robotology/icub-models-generator/issues/242 .
icub-models 2.0.0 changed the name of the FT sensors in the URDF from being named `<identifier>_ft_sensor` (like `l_arm_ft_sensor`, `l_leg_ft_sensor`, ...) to `<identifier>_ft` (like `l_arm_ft`, `l_leg_ft`, ...). 
However, the yarprobotinterface configuration files continued to refer to the sensors as `<identifier>_ft_sensor`, creating errors for software that was trying to match sensors find in URDF and sensors as exposed by the YARP's multipleanalogsensorsserver device.
This PR changes all the instances of iCub configuration files to `<identifier>_ft`, restoring compatibility with icub-models 2.0.0, …
=> Change FT sensors names for compatibility with icub-models >= 2.0.0 and robots-configuration >= 2.5.0 (take two)

CHANGELOG.md, devices/wholeBodyDynamics/app/launch-wholebodydynamics-icub-four-fts.xml, devices/wholeBodyDynamics/app/launch-wholebodydynamics-icub-six-fts-sim.xml, devices/wholeBodyDynamics/app/launch-wholebodydynamics-icub-six-fts.xml, devices/wholeBodyDynamics/app/launch-wholebodydynamics-icub3-sim.xml
I changed the way the config files are called in #173, where I hard-coded the name of the estimator XML file to be called by the launch file. For example `launch-wholebodydynamics-icub-six-fts-sim.xml` calls `wholebodydynamics-icub-external-six-fts-sim.xml`.
But looking at the CMake code, the launch files are installed with the generic name `launch-wholebodydynamics.xml`, and the estimator files are installed as `estimators/wholebodydynamics.xml`, and it's installed for the following real robots `iCubDarmstadt01;iCubGenova02;iCubGenova04;iCubNancy01`, and for the simulated robots: `icubGazeboSim`, `iCubGazeboV2_5`, and `iCubGazeboV3`.
So I reverted to the correct line in this PR.
=> Fix WBD config files broken in #173

CHANGELOG.md
From a project of this size, I this is is perfectly fine to write good PR messages, and the automatically generate the release notes using GitHub functionality, without the need to manually maintain a `CHANGELOG.md` file.
This simplifies the process of making releases.
=> Stop using CHANGELOG.md

CMakeLists.txt, devices/baseEstimatorV1/CMakeLists.txt, devices/baseEstimatorV1/include/Utils.hpp, devices/baseEstimatorV1/include/baseEstimatorV1.h, devices/baseEstimatorV1/src/Utils.cpp, devices/baseEstimatorV1/src/fbeRobotInterface.cpp, devices/genericSensorClient/CMakeLists.txt, devices/virtualAnalogClient/CMakeLists.txt, devices/virtualAnalogRemapper/CMakeLists.txt, devices/wholeBodyDynamics/CMakeLists.txt, devices/wholeBodyDynamics/GravityCompensationHelpers.cpp, devices/wholeBodyDynamics/GravityCompensationHelpers.h, devices/wholeBodyDynamics/SixAxisForceTorqueMeasureHelpers.cpp, devices/wholeBodyDynamics/SixAxisForceTorqueMeasureHelpers.h, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.h, libraries/ctrlLibRT/CMakeLists.txt
* Consolidate find_package CMake calls to a single CMakeLists.txt file and require iDynTree >= 10
* Remove usage of headers deprecated in iDynTree 10 (this was done with a search and replace of `iDynTree/Core/` --> `iDynTree/`, `iDynTree/Model/` --> `iDynTree/`,  `iDynTree/ModelIO/` --> `iDynTree/`, `iDynTree/Estimation/` --> `iDynTree/`, `iDynTree/yarp/` --> `iDynTree/`.
* Switch to always use `iDynTree::Model::sensors()` to access the sensors of a model (done with a search and replace of `m_sensors_list` --> `m_model.sensors()` and `estimator.sensors()` --> `estimator.model().sensors()`
=> Remove iDynTree deprecation warnings

devices/wholeBodyDynamics/README.md, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp, devices/wholeBodyDynamics/WholeBodyDynamicsDevice.h
Fix https://github.com/robotology/whole-body-estimators/issues/179 .
Fix https://github.com/robotology/whole-body-estimators/issues/170 .
This support was not explicitly declared deprecated in wholebodydynamics, however the related interfaces have been deprecated in YARP for a long time. For users interested in using them, please use whole-body-estimators v0.10.0 . The `HW_USE_MAS_IMU` group is now compulsory.
Further cleanup is probably possible (especially in the FT handling logic), but I did not want to mix up the removal of support from the further cleanup.
=> wholebodydynamics: Remove support for reading FT and IMU using IAnalogSensor and IGenericSensor interfaces

.github/workflows/pixi-auto-update-ci.yml, .github/workflows/pixi-ci.yml
This is a bit of iteration on https://github.com/robotology/whole-body-estimators/pull/178 and what is described in https://github.com/prefix-dev/pixi/discussions/910 . 
The idea of https://github.com/robotology/whole-body-estimators/pull/178 is that once in a while we wanted to update the pixi lock file, to ensure that the software does not stop working with new versions of the dependencies. However, periodic update of the pixi lock file have the downside that the repo size continue to grow, even if the repo is not changed at all. Furthermore, the PR for the update for the lock needs to be manually merged, and they add noise in the PRs for the repo.
After a bit of experience with the solution added in https://github.com/robotology/whole-body-estimators/pull/178, I thought of another …
=> Remove scheduled pixi auto-update and add scheduled build with latest dependencies

devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp
This is a bug found by @LoreMoretti , basically he was trying to remote just the upper_leg FTs from ergocub from the estimation, but the wbd launch was failing with:
~~~
yError() << "WholeBodyDynamicsDevice::attachAll Invalid number of MAS FT sensors after remapper";
~~~
However, the check does not make a lot of sense. `nrMASFTSensors` is the total number of FT sensors in all the devices attached to wbd (for ergocub 8), while ` remappedMASInterfaces.ftMultiSensors->getNrOfSixAxisForceTorqueSensors()` and `ftMultipleAnalogSensorNames.size()` are the actual number of sensors considered (removing the `upper_leg` fts as @LoreMoretti was doing, 6).
To be honest, I am wondering how we were removing the FT from the estimation with this bug. Perhaps in all other cases were also either avoiding to …
=> WholeBodyDynamicsDevice: Remove meaningless check that total number FTs in attached device match the total number of FTs consired by estimation
